<?php

	register_field_group(array (
		'id' => 'acf_opendmo-post-info',
		'title' => 'OpenDMO Post Info',
		'fields' => array (
            array (
	            "key" => "field_opendmo_info_settings",
	            "label" => "Post Settings",
	            "name" => "",
	            "type" => "tab",
            ),
			array (
				'key' => 'field_57ab4141bee0e',
				'label' => 'Verified Page',
				'name' => 'verified_page',
				'type' => 'true_false',
				'message' => 'Hours and contact information for this location have been verified.',
				'default_value' => 0,
			),
			array (
				'key' => 'field_56df949cb0e5f',
				'label' => 'Pin to Home Page',
				'name' => 'pin_home',
				'type' => 'true_false',
				'instructions' => 'Include this post in the featured section of the home page?',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_57eb824ae1f2c',
				'label' => 'Is Event Venue',
				'name' => 'is_venue',
				'type' => 'true_false',
				'instructions' => 'Is this an event venue?',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_574f10ca6858c',
				'label' => 'Home Page Expiration',
				'name' => 'pin_home_expire',
				'type' => 'date_picker',
				'instructions' => 'Will disappear from home page at 12am on date selected. Leave blank to never expire.',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_56df949cb0e5f',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'date_format' => 'yymmdd',
				'display_format' => 'dd/mm/yy',
				'first_day' => 1,
			),
			array (
				'key' => 'field_577321f84a395',
				'label' => 'Hide Author & Date',
				'name' => 'hide_author_date',
				'type' => 'true_false',
				'instructions' => 'Select to hide the author and date of this post ',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_57b710e509aab',
				'label' => 'Move Author & Date to Bottom',
				'name' => 'bottom_author',
				'type' => 'true_false',
				'instructions' => 'Select to move the author and date of this post to the bottom of the page<br /><small>(Default on Pages, Events and Stay)</small>',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_577321f84a395',
							'operator' => '!=',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'message' => '',
				'default_value' => 0,
			),
            array (
	            "key" => "field_opendmo_info_hours",
	            "label" => "Hours",
	            "name" => "",
	            "type" => "tab",
            ),
			array (
				'key' => 'field_57879321b9bc7',
				'label' => 'Hours',
				'name' => 'bizhours',
				'type' => 'textarea',
				'instructions' => 'Example: Monday-Friday, 8:30am-5pm',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
            array (
	            "key" => "field_opendmo_info_phone",
	            "label" => "Phone",
	            "name" => "",
	            "type" => "tab",
            ),
			array (
				'key' => 'field_56bcdfaa84ddb',
				'label' => 'Phone',
				'name' => 'phone',
				'type' => 'text',
				'instructions' => 'Example: (864) 123-4567',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
            array (
	            "key" => "field_opendmo_info_address",
	            "label" => "Addresses",
	            "name" => "",
	            "type" => "tab",
            ),
			array (
				'key' => 'field_56b3fa4a7e19b',
				'label' => 'Address',
				'name' => 'address',
				'type' => 'text',
				'instructions' => 'Example: 123 W Main St',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56b3fa7e7e19c',
				'label' => 'City',
				'name' => 'city',
				'type' => 'select',
				'instructions' => 'Select a city or town corresponding to the physical address.',
				'choices' => array (
					'New York/NY' => 'New York',

				),
				'default_value' => '',
				'allow_null' => 1,
				'multiple' => 0,
			),
			array (
				'key' => 'field_56bcb3c4d811b',
				'label' => 'Zip Code',
				'name' => 'zip',
				'type' => 'text',
				'instructions' => 'Enter the zip code of the physical address',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (

					),
					'allorany' => 'any',
				),
				'default_value' => '',
				'placeholder' => 12345,
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => 5,
			),
			array (
				'key' => 'field_579b6ee0dfbf1',
				'label' => 'Mailing Address',
				'name' => 'mail_address',
				'type' => 'text',
				'instructions' => 'Example: PO Box 1234',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_579b6f9bdfbf2',
				'label' => 'Mailing City',
				'name' => 'mail_city',
				'type' => 'select',
				'instructions' => 'Select a city or town corresponding to the mailing address.',
				'choices' => array (
					'Chicago/IL' => 'Chicago',
				),
				'default_value' => '',
				'allow_null' => 1,
				'multiple' => 0,
			),
			array (
				'key' => 'field_579b6fbfdfbf3',
				'label' => 'Mailing Zip Code',
				'name' => 'mail_zip',
				'type' => 'text',
				'instructions' => 'Enter the zip code of the physical address',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
					),
					'allorany' => 'any',
				),
				'default_value' => '',
				'placeholder' => 12345,
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => 5,
			),
            array (
	            "key" => "field_opendmo_info_gps",
	            "label" => "GPS",
	            "name" => "",
	            "type" => "tab",
            ),
			array (
				'key' => 'field_578673873f0f4',
				'label' => 'GPS Latitude (Parking Area)',
				'name' => 'gps_parking_lat',
				'type' => 'text',
				'instructions' => 'Example: 34.696458',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_578673953f0f5',
				'label' => 'GPS Longitude (Parking Area)',
				'name' => 'gps_parking_long',
				'type' => 'text',
				'instructions' => 'Example: -82.838723',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_578673a23f0f6',
				'label' => 'GPS Latitude (Actual Location)',
				'name' => 'gps_actual_lat',
				'type' => 'text',
				'instructions' => 'Example: 34.708957',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_578673ae3f0f7',
				'label' => 'GPS Longitude (Actual Location)',
				'name' => 'gps_actual_long',
				'type' => 'text',
				'instructions' => 'Example: -82.820388',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
            array (
	            "key" => "field_opendmo_info_links",
	            "label" => "Links",
	            "name" => "",
	            "type" => "tab",
            ),
			array (
				'key' => 'field_56b3f3e45c1fe',
				'label' => 'Official Website',
				'name' => 'website',
				'type' => 'text',
				'instructions' => 'The official website of the primary subject within this post',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'http://',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
            array (
	            "key" => "field_opendmo_info_social",
	            "label" => "Social",
	            "name" => "",
	            "type" => "tab",
            ),
			array (
				'key' => 'field_56b3f4a35c1ff',
				'label' => 'Facebook Page',
				'name' => 'facebook',
				'type' => 'text',
				'instructions' => 'URL of the Facebook Page most relevant to the post (https://facebook.com/[ONLY-INCLUDE-THIS-PART])',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'https://facebook.com/',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_56b3f4f65c200',
				'label' => 'Twitter Profile',
				'name' => 'twitter',
				'type' => 'text',
				'instructions' => 'URL of the Twitter profile most relevant to the post (Only include username without the @ symbol)',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'https://twitter.com/',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5774483e5fec3',
				'label' => 'Instagram Profile',
				'name' => 'instagram',
				'type' => 'text',
				'instructions' => 'URL of the Instagram profile most relevant to the post (Only include username without the @ symbol)',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'https://instagram.com/',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_577448785fec4',
				'label' => 'YouTube Channel',
				'name' => 'youtube',
				'type' => 'text',
				'instructions' => 'URL of the YouTube channel most relevant to the post (https://youtube.com/[ONLY-INCLUDE-THIS-PART])',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'https://youtube.com/',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57a34dca5ba43',
				'label' => 'TripAdvisor Page',
				'name' => 'tripadvisor',
				'type' => 'text',
				'instructions' => 'URL of the TripAdvisor page most relevant to the post (https://tripadvisor.com/[ONLY-INCLUDE-THIS-PART])',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'https://tripadvisor.com/',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
            array (
	            "key" => "field_opendmo_info_reviews",
	            "label" => "Reviews",
	            "name" => "",
	            "type" => "tab",
            ),
			array (
				'key' => 'field_57b71122bd902',
				'label' => 'Google Place ID',
				'name' => 'google_place_id',
				'type' => 'text',
				'instructions' => 'Find the ID of a Place through the <a href="https://developers.google.com/maps/documentation/javascript/examples/places-placeid-finder" target="_blank">Google PlaceID Finder Tool</a>. Example: ChIJgzjVcgxeWIgR_HSag0BYocs',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57d2f3dc28577',
				'label' => 'Make Google Reviews Private',
				'name' => 'google_private',
				'type' => 'true_false',
				'message' => 'Check this box to only allow admins to see Google reviews',
				'default_value' => 0,
			),
		),
		'location' => fields_location(0),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (	),
		),
		'menu_order' => 0,
	));


?>
